### PR TITLE
Updated And Advanced understanding Calculator.

### PR DESCRIPTION
**Pull request by MehulGupta21**
I have advanced up the calculator and can advance it even more if you want please let me know mastermehul20003@gmail.com I made it in a way that the user enter his query and the calculator processes it, I can make it hands-free if you want

### CODE REVIEW

**Comment by JamBot3000** [comment]
LGTM! Thankyou for making these changes in one PR :)

**Comment by JamBot3000** [comment]
Please make a seperate file for this one thankyou! :)

**Comment by MehulGupta21** [comment]
Can anyone please tell me Why is my merge blocked?

**Comment by JamBot3000** [comment]
Ah sorry, your merge isn't blocked. Are you referring to the branch conflict? I'll fix it don't worry :) I'm just busy with school and stuff at the moment and about to leave the house. Will fix and merge for you when I'm home dw dude :)

**Comment by MehulGupta21** [comment]
Oh Okay, sir thank you very much. Looking forward to it :)

**Comment by JamBot3000** [comment]
I'm not sure what the problem is here rn lol. Sorry quite tired, tried deleting the file causing issues but it didn't help. Will look into it more though dw. It might help if instead of trying to edit an existing file, you make a separate one for the "advanced calculator"

**Pull request merged**
