### PR TITLE
thought cyclegan might be cool

### PR DESCRIPTION
**Pull request by gittygupta**
issue #3

### CODE REVIEW

**Review by JamBot3000 — CHANGES_REQUESTED** [review]
Hello. please upload the .py instead of the notebook file :)

**Comment by JamBot3000** [comment]
This PR will be marked as invalid until changes are made and I confirm the code is not reused

**Comment by gittygupta** [comment]
> Hello. please upload the .py instead of the notebook file :)

Changes have been made.

**Comment by gittygupta** [comment]
> This PR will be marked as invalid until changes are made and I confirm the code is not reused

Please consider merging if you think it will be useful and do remove the invalid label if you think requested changes have been made. Thanks in advance. :)

**Comment by JamBot3000** [comment]
Sorry but you already have this in a repo on your profile

**Comment by gittygupta** [comment]
> Sorry but you already have this in a repo on your profile

No, I have a repo on GANs because I am currently working a lot on GANs. CycleGAN is the most recent one that I have learned. Yet if you don't wanna incorporate or remove the invalid label, that's totally your choice

**Pull request closed without merging**
