### PR TITLE
Merge Sort with random numbers

### PR DESCRIPTION
**Pull request by rudrajit1729**
Generates random numbers and applies merge sort to arrange them in ascending order. 
The program in C takes numbers from users instead of generating random numbers.

### CODE REVIEW

**Comment by rudrajit1729** [comment]
Merge Sort with random numbers #9

**Comment by rudrajit1729** [comment]
I learnt about using time utility library in cpp as a new method to generate random numbers using CPU time. randomizing based on time stamps is a really cool feature in CPP had fun using this.

**Comment by rudrajit1729** [comment]
@themonkeyhacker please review and suggest changes if any.

**Comment by JamBot3000** [comment]
Sorry but I believe this to be below your skill level. This repository is for beginners and people learning how to code. Marked as invalid

**Comment by rudrajit1729** [comment]
Please revert the changes @themonkeyhacker . This is an Invalid PR and shouldn't be merged into master. I understand it is for beginners but at that time it was only issue which was not assigned. Thought of giving it a try.

**Comment by rudrajit1729** [comment]
Please revert the changes @JamBot3000 . This is an Invalid PR and shouldn't be merged into master. I understand it is for beginners but at that time it was only issue which was not assigned. Thought of giving it a try. No worries any way.

**Pull request merged**
