### PR TITLE
Added ASCII art generator python file

### PR DESCRIPTION
**Pull request by RadientBrain**
I have added the ascii art generator python file.
Just give the path in the input to the image and it will generate ascii art for that image.
This resolves the issue no #23 by @aljazmedic

### CODE REVIEW

**Comment by JamBot3000** [comment]
Stolen from [https://medium.com/javascript-dots/python-ascii-art-generator-60ba9eb559d7](url)

**Comment by Owez** [comment]
Link is invalid, goes to https://github.com/JamBot3000/Hacktober-Challenges/pull/url

**Comment by RadientBrain** [comment]
@JamBot3000 I didn't take the code from <a href="https://medium.com/javascript-dots/python-ascii-art-generator-60ba9eb559d7">here</a> but followed a video tutorial by the youtube channel of ***KITE***(<a href="https://www.youtube.com/watch?v=v_raWlX7tZY">here</a>) to actually make this code.

Is it invalid to take help from the other resources to make ***PR***?

Please tell as I am not that much experienced with PRs. (@Owez @JamBot3000 )

**Comment by JamBot3000** [comment]
Normally it would be fine, so long as it actually fixes the issue it deals with. But this repo is different as the issues aren't actually necessary, just tasks for beginners to attempt to complete to encourage open source development. Taking help is one thing, but you didn't really change anything up so for all I know it could just be a copy then PR in order to 1up for hacktoberfest. The README specifically says do not re-use code because of this problem. If the challenge is too hard feel free to attempt any others :)

**Comment by JamBot3000** [comment]
If I allowed any PR that had just gotten code from elsewhere, and I didn't encourage people to find their own ways to solve a challenge, then this repo would become invalid for hacktoberfest stuff, as I would have to accept this same code over and over again if people kept submitting it. I'll gladly reopen the pull and merge if you really want, but it won't count towards hacktoberfest.

**Pull request closed without merging**
