### PR TITLE
Magic8ball

### PR DESCRIPTION
**Pull request by shloka-gupta**
This is the first time i learnt about how to create a magic8ball it was fun

### CODE REVIEW

**Comment by mariaachim** [comment]
thank you for your pr! this has been marked as invalid as i think this is below your skill level so it will not count towards hacktoberfest

**Comment by gittygupta** [comment]
lol what a loser, merges yet marks invalid XD. And he thinks he knows our skill level, whereas he is the one posting PRs on his friends repos, gutless.

**Comment by JamBot3000** [comment]
> lol what a loser, merges yet marks invalid XD. And he thinks he knows our skill level, whereas he is the one posting PRs on his friends repos, gutless.

Hello! Whether we merge or not doesn't really matter. But this was definitely below his skill level. I know because this code is found here: [https://github.com/chicken-biryani/Python-Scripts/blob/master/magic8ball.py](url)
and also here: [https://www.pythonforbeginners.com/code-snippets-source-code/magic-8-ball-written-in-python](url)
Also other projects on his profile show reasons why this guy is skilled, and why he didn't learn anything from this. I make sure to go through each PR individually and judge it for myself. To prevent people from spamming PRs for no reason. This repo is meant for beginners to learn.

**Comment by gittygupta** [comment]
> > lol what a loser, merges yet marks invalid XD. And he thinks he knows our skill level, whereas he is the one posting PRs on his friends repos, gutless.
> 
> Hello! Whether we merge or not doesn't really matter. But this was definitely below his skill level. I know because this code is found here: [https://github.com/chicken-biryani/Python-Scripts/blob/master/magic8ball.py](url)
> and also here: [https://www.pythonforbeginners.com/code-snippets-source-code/magic-8-ball-written-in-python](url)
> Also other projects on his profile show reasons why this guy is skilled, and why he didn't learn anything from this. I make sure to go through each PR individually and judge it for myself. To prevent people from spamming PRs for no reason. This repo is meant for beginners to learn.

"Judging"? Big words my friend. Peace ✌ ☮

**Pull request merged**
